# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: 'sudo apt update'
  displayName: 'update'

- script: 'sudo apt install nodejs'
  displayName: 'install node'

- script: 'sudo apt install npm'
  displayName: 'install npm'

- script: 'npm install -g botium-cli'
  displayName: 'Command Line Script'

- script: 'botium-cli run'
  displayName: 'Command Line Script'
  workingDirectory: aurora-pt\botium-connector-directline3\samples\convo\spec\convo

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  


